export interface ScholarshipInput {
  name: string;
  amount: number;
  description: string;
  eligibility: string;
  deadline: Date;
  tags: string[];
  minPercentage: number | null;
  maxIncome: number | null;
  categories: string[];
  states: string[];
  schoolTypes: string[];
}

export const scholarshipsData: ScholarshipInput[] = [
  {
    name: "NSP Central Sector Scheme of Scholarship (CSSS)",
    amount: 20000,
    description: "For college and university students with outstanding performance in Class 12 board exams.",
    eligibility: "Top 20th percentile in Class 12, family income under 4.5 LPA.",
    deadline: new Date("2026-10-31"),
    tags: ["Merit Based", "Government", "Higher Education"],
    minPercentage: 80,
    maxIncome: 450000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "NSP Post-Matric Scholarship for SC Students",
    amount: 12000,
    description: "Centrally sponsored scheme to support post-matriculation education of Scheduled Caste students.",
    eligibility: "SC category students, passed Class 10/12, family income under 2.5 LPA.",
    deadline: new Date("2026-11-15"),
    tags: ["Government", "SC Category", "Need Based"],
    minPercentage: 50,
    maxIncome: 250000,
    categories: ["SC"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "NSP Post-Matric Scholarship for ST Students",
    amount: 12000,
    description: "Financial assistance provided by the Ministry of Tribal Affairs to Scheduled Tribe students.",
    eligibility: "ST category students, passed Class 10/12, family income under 2.5 LPA.",
    deadline: new Date("2026-11-15"),
    tags: ["Government", "ST Category", "Need Based"],
    minPercentage: 50,
    maxIncome: 250000,
    categories: ["ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "NSP Merit-Cum-Means Scholarship for Minorities (MOMA)",
    amount: 30000,
    description: "Support for professional and technical courses for students belonging to minority communities.",
    eligibility: "Minority students (Muslim, Christian, Sikh, etc.) with 50%+ marks, income under 2.5 LPA.",
    deadline: new Date("2026-10-15"),
    tags: ["Government", "Minority", "Technical"],
    minPercentage: 50,
    maxIncome: 250000,
    categories: ["General", "OBC"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Begum Hazrat Mahal National Scholarship",
    amount: 12000,
    description: "Scholarship for meritorious girls belonging to national minority communities.",
    eligibility: "Minority girl students studying in Class 9-12 with 50%+ marks, income under 2 LPA.",
    deadline: new Date("2026-09-30"),
    tags: ["Government", "Girls", "Minority"],
    minPercentage: 50,
    maxIncome: 200000,
    categories: ["General", "OBC"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided"]
  },
  {
    name: "AICTE Pragati Scholarship for Girl Students",
    amount: 50000,
    description: "Scholarship to promote technical education among girls admitted to technical degree courses.",
    eligibility: "Girl students admitted in 1st year of technical degree with family income under 8 LPA.",
    deadline: new Date("2026-10-31"),
    tags: ["Girls", "Technology", "Government", "Merit Based"],
    minPercentage: 70,
    maxIncome: 800000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "AICTE Saksham Scholarship for Specially Abled Students",
    amount: 50000,
    description: "Support for specially-abled students to pursue technical education at degree/diploma levels.",
    eligibility: "Disabled students (40%+ disability) admitted to AICTE approved technical courses, income under 8 LPA.",
    deadline: new Date("2026-10-31"),
    tags: ["Disabled", "Government", "Technical"],
    minPercentage: 50,
    maxIncome: 800000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Tata Trust Medical and Engineering Scholarship",
    amount: 40000,
    description: "Financial grant by Tata Trusts for undergraduate engineering and medical studies in India.",
    eligibility: "Students pursuing engineering or medicine with 70%+ marks, income under 4 LPA.",
    deadline: new Date("2026-11-30"),
    tags: ["Need Based", "Engineering", "Medical", "Private Sector"],
    minPercentage: 70,
    maxIncome: 400000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "HDFC Bank Parivartan's ECS Scholarship",
    amount: 35000,
    description: "Support for school, undergraduate, and postgraduate students from economically weaker sections.",
    eligibility: "Passed previous exam with 60%+ marks, annual family income under 2.5 LPA.",
    deadline: new Date("2026-09-30"),
    tags: ["Need Based", "Private Sector", "Education Support"],
    minPercentage: 60,
    maxIncome: 250000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "LIC Golden Jubilee Scholarship",
    amount: 20000,
    description: "Scholarship for students pursuing higher education in government or private colleges.",
    eligibility: "Class 12 passed with 60%+ marks, family income under 2.5 LPA.",
    deadline: new Date("2026-12-15"),
    tags: ["Need Based", "Higher Education"],
    minPercentage: 60,
    maxIncome: 250000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Kotak Kanya Scholarship",
    amount: 75000,
    description: "Financial assistance and mentoring for meritorious girl students from EWS sections.",
    eligibility: "Girl students, Class 12 score 85%+, family income under 6 LPA.",
    deadline: new Date("2026-10-15"),
    tags: ["Girls", "Merit Based", "Private Sector"],
    minPercentage: 85,
    maxIncome: 600000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "SBIF Asha Scholarship Program",
    amount: 15000,
    description: "SBI Foundation scheme to support school students from low-income families.",
    eligibility: "Class 6-12 students with 75%+ marks, family income under 3 LPA.",
    deadline: new Date("2026-10-10"),
    tags: ["Need Based", "School Level", "Private Sector"],
    minPercentage: 75,
    maxIncome: 300000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided"]
  },
  {
    name: "Keep India Smiling Foundational Scholarship (Colgate)",
    amount: 30000,
    description: "Financial aid for students pursuing 3-year graduation or vocational courses.",
    eligibility: "Class 12 passed with 60%+, annual family income under 5 LPA.",
    deadline: new Date("2026-09-15"),
    tags: ["Need Based", "Undergraduate", "Private Sector"],
    minPercentage: 60,
    maxIncome: 500000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Swami Vivekananda Merit Cum Means Scholarship (WB)",
    amount: 60000,
    description: "West Bengal government scholarship for meritorious students pursuing higher studies.",
    eligibility: "West Bengal domicile, 60%+ in Class 12, family income under 2.5 LPA.",
    deadline: new Date("2026-11-30"),
    tags: ["State Govt", "Merit", "Need Based"],
    minPercentage: 60,
    maxIncome: 250000,
    categories: ["General", "OBC", "SC", "ST"],
    states: ["West Bengal"],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "SSP Post Matric Scholarship (Karnataka)",
    amount: 25000,
    description: "Karnataka State Portal scholarship for backward classes and minority categories.",
    eligibility: "Karnataka domicile, backward category, passed previous exam, income under 2.5 LPA.",
    deadline: new Date("2026-11-30"),
    tags: ["State Govt", "Need Based"],
    minPercentage: 50,
    maxIncome: 250000,
    categories: ["OBC", "SC", "ST"],
    states: ["Karnataka"],
    schoolTypes: ["Govt", "Govt Aided"]
  },
  {
    name: "MahaDBT Post Matric Scholarship (Maharashtra)",
    amount: 20000,
    description: "Maharashtra state scholarship for students of OBC/VJNT/SBC categories.",
    eligibility: "Maharashtra domicile, category OBC/VJNT, income under 8 LPA.",
    deadline: new Date("2026-12-31"),
    tags: ["State Govt", "OBC Category", "Need Based"],
    minPercentage: 50,
    maxIncome: 800000,
    categories: ["OBC", "SC", "ST"],
    states: ["Maharashtra"],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "UP Post Matric Scholarship (Uttar Pradesh)",
    amount: 15000,
    description: "Uttar Pradesh government scheme for EWS, OBC, and SC/ST students.",
    eligibility: "UP domicile, passed last exam, family income under 2 LPA.",
    deadline: new Date("2026-12-10"),
    tags: ["State Govt", "Need Based"],
    minPercentage: 55,
    maxIncome: 200000,
    categories: ["General", "OBC", "SC", "ST"],
    states: ["Uttar Pradesh"],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Bihar Post-Matric Scholarship (OBC/EBC)",
    amount: 15000,
    description: "Bihar government portal for BC and EBC category students for technical and general studies.",
    eligibility: "Bihar domicile, OBC/EBC category, family income under 3 LPA.",
    deadline: new Date("2026-10-31"),
    tags: ["State Govt", "OBC Category", "Need Based"],
    minPercentage: 50,
    maxIncome: 300000,
    categories: ["OBC"],
    states: ["Bihar"],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Rajasthan Post-Matric Scholarship (SC/ST)",
    amount: 18000,
    description: "Rajasthan Social Justice and Empowerment Department scholarship for SC/ST students.",
    eligibility: "Rajasthan domicile, SC/ST category, family income under 2.5 LPA.",
    deadline: new Date("2026-11-30"),
    tags: ["State Govt", "SC Category", "ST Category"],
    minPercentage: 50,
    maxIncome: 250000,
    categories: ["SC", "ST"],
    states: ["Rajasthan"],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Santoor Scholarship for Girls",
    amount: 24000,
    description: "Wipro Cares support for girl students from underprivileged backgrounds in select states.",
    eligibility: "Girl students from AP, Telangana, or Karnataka, passed Class 12, income under 4 LPA.",
    deadline: new Date("2026-09-15"),
    tags: ["Girls", "Need Based", "Private Sector"],
    minPercentage: 60,
    maxIncome: 400000,
    categories: ["General", "OBC", "SC", "ST"],
    states: ["Karnataka", "Andhra Pradesh", "Telangana"],
    schoolTypes: ["Govt", "Govt Aided"]
  },
  {
    name: "Aditya Birla Capital Scholarship Scheme",
    amount: 60000,
    description: "One-time scholarship for school and undergraduate professional course students.",
    eligibility: "Passed previous exam with 60%+, family income under 6 LPA.",
    deadline: new Date("2026-10-15"),
    tags: ["Need Based", "Undergraduate", "Private Sector"],
    minPercentage: 60,
    maxIncome: 600000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "L'Oréal India For Young Women In Science Scholarship",
    amount: 250000,
    description: "Highly competitive scholarship for girls aiming to pursue undergraduate science courses.",
    eligibility: "Girl students, Class 12 science percentage 85%+, family income under 6 LPA.",
    deadline: new Date("2026-10-15"),
    tags: ["Girls", "Science", "Merit Based", "Private Sector"],
    minPercentage: 85,
    maxIncome: 600000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Sitaram Jindal Foundation Scholarship",
    amount: 24000,
    description: "General merit-cum-means scholarship for school, ITI, diploma, and college degrees.",
    eligibility: "Min 70% in previous exam (65% for girls), family income under 2.5 LPA.",
    deadline: new Date("2026-12-31"),
    tags: ["Need Based", "School Level", "College Level"],
    minPercentage: 70,
    maxIncome: 250000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Raman Kant Munjal Scholarship",
    amount: 50000,
    description: "For students pursuing finance, management, or commerce-related undergraduate courses.",
    eligibility: "Class 12 score 80%+, annual family income under 4 LPA.",
    deadline: new Date("2026-10-31"),
    tags: ["Merit", "Management", "Finance"],
    minPercentage: 80,
    maxIncome: 400000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Prime Minister's Scholarship Scheme (PMSS)",
    amount: 36000,
    description: "Welfare scheme to support technical and professional courses for wards of ex-servicemen.",
    eligibility: "Wards of ex-servicemen, passed Class 12 with 60%+ marks.",
    deadline: new Date("2026-11-30"),
    tags: ["Government", "Defense Ward", "Professional"],
    minPercentage: 60,
    maxIncome: null,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "INSPIRE Scholarship (SHE)",
    amount: 80000,
    description: "Department of Science and Technology scholarship for students pursuing basic and natural sciences.",
    eligibility: "Top 1% rank in Class 12 Board examinations, studying basic science courses.",
    deadline: new Date("2026-11-15"),
    tags: ["Science", "Merit Based", "Government"],
    minPercentage: 90,
    maxIncome: null,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Adani Gyan Jyoti Scholarship",
    amount: 50000,
    description: "Support for first-year engineering, medical, or law students from specific EWS regions.",
    eligibility: "Domicile of GJ, RJ, or MH, JEE/NEET qualified, income under 4.5 LPA.",
    deadline: new Date("2026-09-30"),
    tags: ["Need Based", "Engineering", "Medical", "Private Sector"],
    minPercentage: 75,
    maxIncome: 450000,
    categories: ["General", "OBC", "SC", "ST"],
    states: ["Gujarat", "Rajasthan", "Maharashtra"],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Rolls-Royce Unnati Scholarship for Women",
    amount: 35000,
    description: "Support for girl students pursuing engineering degree courses from AICTE colleges.",
    eligibility: "Girl students, pursuing 1st/2nd year B.Tech, 60%+ in Class 12.",
    deadline: new Date("2026-08-31"),
    tags: ["Girls", "Engineering", "Technical"],
    minPercentage: 60,
    maxIncome: null,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Siemens Scholarship Program",
    amount: 50000,
    description: "Support for first-year government engineering college students from economically backward sections.",
    eligibility: "First-year engineering, 60%+ in Class 12, family income under 2 LPA.",
    deadline: new Date("2026-08-15"),
    tags: ["Engineering", "First Generation", "Need Based"],
    minPercentage: 60,
    maxIncome: 200000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided"]
  },
  {
    name: "KC Mahindra Trust Scholarship",
    amount: 100000,
    description: "Scholarship for diploma and degree courses for EWS students in technical streams.",
    eligibility: "Passed Class 10/12 with 65%+, family income under 4 LPA.",
    deadline: new Date("2026-09-30"),
    tags: ["Need Based", "Higher Education", "Private Sector"],
    minPercentage: 65,
    maxIncome: 400000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "ONGC Scholarship Scheme for SC/ST Students",
    amount: 48000,
    description: "ONGC Foundation grant for SC/ST students pursuing engineering or MBBS.",
    eligibility: "SC/ST category students in professional courses with 60%+, family income under 4.5 LPA.",
    deadline: new Date("2026-10-31"),
    tags: ["Government", "SC Category", "ST Category", "Professional"],
    minPercentage: 60,
    maxIncome: 450000,
    categories: ["SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "FICCI Scholarship Scheme",
    amount: 50000,
    description: "FICCI support for girl students pursuing general undergraduate degrees.",
    eligibility: "Girl students, 1st year graduation, 75%+ marks, family income under 3 LPA.",
    deadline: new Date("2026-09-30"),
    tags: ["Need Based", "Girls", "Private Sector"],
    minPercentage: 75,
    maxIncome: 300000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "DLF Foundation Raghvendra Scholarship",
    amount: 40000,
    description: "Financial aid for professional undergraduate courses for EWS students in NCR.",
    eligibility: "Domicile of HR, UP, or Delhi, 75%+ in Class 12, family income under 3 LPA.",
    deadline: new Date("2026-10-15"),
    tags: ["Need Based", "Professional", "Private Sector"],
    minPercentage: 75,
    maxIncome: 300000,
    categories: ["General", "OBC", "SC", "ST"],
    states: ["Haryana", "Uttar Pradesh", "Delhi"],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "JSW Udaan Scholarship",
    amount: 30000,
    description: "Corporate social responsibility initiative of JSW to support higher education.",
    eligibility: "Undergraduate degree student, 60%+ in Class 12, family income under 8 LPA.",
    deadline: new Date("2026-09-30"),
    tags: ["Need Based", "Undergraduate", "Private Sector"],
    minPercentage: 60,
    maxIncome: 800000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Reliance Foundation Undergraduate Scholarships",
    amount: 200000,
    description: "Generous scholarship for outstanding undergraduate students across all streams.",
    eligibility: "1st year undergraduate, 60%+ in Class 12, family income under 15 LPA.",
    deadline: new Date("2026-10-31"),
    tags: ["Merit", "Need Based", "Private Sector"],
    minPercentage: 60,
    maxIncome: 1500000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "Indira Gandhi Single Girl Child Scholarship",
    amount: 36200,
    description: "UGC scholarship to support postgraduate education of single girl children.",
    eligibility: "Only girl child of a family, admitted to 1st year PG course, 60%+ in graduation.",
    deadline: new Date("2026-10-30"),
    tags: ["Government", "Girls", "Postgraduate"],
    minPercentage: 60,
    maxIncome: null,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "NSP National Means Cum Merit Scholarship (NMMSS)",
    amount: 12000,
    description: "Centrally sponsored scheme for school students to prevent dropouts in Class 8.",
    eligibility: "Class 9 students with 55%+ marks in Class 8, family income under 3.5 LPA.",
    deadline: new Date("2026-10-15"),
    tags: ["Government", "Need Based", "School Level"],
    minPercentage: 55,
    maxIncome: 350000,
    categories: ["General", "OBC", "SC", "ST"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided"]
  },
  {
    name: "Medhabruti Scholarship (Odisha)",
    amount: 10000,
    description: "Odisha State Government scholarship for meritorious students pursuing UG/PG courses.",
    eligibility: "Odisha domicile, 60%+ marks, annual family income under 6 LPA.",
    deadline: new Date("2026-11-15"),
    tags: ["State Govt", "Merit", "Higher Education"],
    minPercentage: 60,
    maxIncome: 600000,
    categories: ["General", "OBC", "SC", "ST"],
    states: ["Odisha"],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "SSP Post Matric Scholarship SC/ST (Karnataka)",
    amount: 30000,
    description: "Karnataka Social Welfare Department support for SC/ST students in higher studies.",
    eligibility: "Karnataka domicile, SC/ST category, family income under 2.5 LPA.",
    deadline: new Date("2026-11-30"),
    tags: ["State Govt", "SC Category", "ST Category"],
    minPercentage: 50,
    maxIncome: 250000,
    categories: ["SC", "ST"],
    states: ["Karnataka"],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  },
  {
    name: "NSP Post-Matric Scholarship for OBC Students",
    amount: 10000,
    description: "Centrally assisted scheme to support the education of Other Backward Class students.",
    eligibility: "OBC category, passed Class 10/12, family income under 1.5 LPA.",
    deadline: new Date("2026-11-15"),
    tags: ["Government", "OBC Category", "Need Based"],
    minPercentage: 50,
    maxIncome: 150000,
    categories: ["OBC"],
    states: [],
    schoolTypes: ["Govt", "Govt Aided", "Private"]
  }
];
